/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author Tichi
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonDraw = new javax.swing.JButton();
        Deck = new javax.swing.JLabel();
        buttonDiscard = new javax.swing.JButton();
        PlayerCard1 = new javax.swing.JLabel();
        PlayerCard2 = new javax.swing.JLabel();
        PlayerCard4 = new javax.swing.JLabel();
        PlayerCard3 = new javax.swing.JLabel();
        Player2Card1 = new javax.swing.JLabel();
        Player2Card2 = new javax.swing.JLabel();
        Player2Card3 = new javax.swing.JLabel();
        Player2Card4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textGameLog = new javax.swing.JTextArea();
        buttonPeek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonDraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        buttonDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDrawActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDraw, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 140, 180));

        Deck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Deck/13_1.png"))); // NOI18N
        getContentPane().add(Deck, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 254, -1, 175));

        buttonDiscard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/4.png"))); // NOI18N
        buttonDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiscardActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDiscard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 140, 180));

        PlayerCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        PlayerCard1.setText("Player Card 1");
        getContentPane().add(PlayerCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 135, 168));

        PlayerCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        PlayerCard2.setText("Player Card 2");
        getContentPane().add(PlayerCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 138, 168));

        PlayerCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        PlayerCard4.setText("Player Card 4");
        getContentPane().add(PlayerCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 130, 168));

        PlayerCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        PlayerCard3.setText("Player Card 3");
        getContentPane().add(PlayerCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 137, 168));

        Player2Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        Player2Card1.setText("Computer Card 1");
        getContentPane().add(Player2Card1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 11, 136, 168));

        Player2Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        Player2Card2.setText("Computer Card 2");
        getContentPane().add(Player2Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 11, 136, 168));

        Player2Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        Player2Card3.setText("Computer Card 3");
        getContentPane().add(Player2Card3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 11, 129, 168));

        Player2Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13.png"))); // NOI18N
        Player2Card4.setText("Computer Card 4");
        getContentPane().add(Player2Card4, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 11, 129, 168));

        textGameLog.setColumns(20);
        textGameLog.setRows(5);
        jScrollPane1.setViewportView(textGameLog);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 197, 226, 290));

        buttonPeek.setText("Peek");
        getContentPane().add(buttonPeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 92, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiscardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDiscardActionPerformed

    private void buttonDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDrawActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDrawActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Deck;
    private javax.swing.JLabel Player2Card1;
    private javax.swing.JLabel Player2Card2;
    private javax.swing.JLabel Player2Card3;
    private javax.swing.JLabel Player2Card4;
    private javax.swing.JLabel PlayerCard1;
    private javax.swing.JLabel PlayerCard2;
    private javax.swing.JLabel PlayerCard3;
    private javax.swing.JLabel PlayerCard4;
    private javax.swing.JButton buttonDiscard;
    private javax.swing.JButton buttonDraw;
    private javax.swing.JButton buttonPeek;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textGameLog;
    // End of variables declaration//GEN-END:variables
}
