/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

public class PeekInstructionDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form PeekInstructionDialog
     */
    public PeekInstructionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peekInstruction_jbutton_ok = new javax.swing.JButton();
        scrollPeek = new javax.swing.JScrollPane();
        peekInstruction_jtextarea_instr1 = new javax.swing.JTextArea();
        scrollPowerCards = new javax.swing.JScrollPane();
        peekInstruction_jtextarea_instr2 = new javax.swing.JTextArea();
        peekInstruction_jlabel_label1 = new javax.swing.JLabel();
        peekInstruction_jlabel_graphic2 = new javax.swing.JLabel();
        peekInstruction_jlabel_graphic1 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        peekInstruction_jbutton_ok.setText("OK");
        peekInstruction_jbutton_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peekInstruction_jbutton_okActionPerformed(evt);
            }
        });

        peekInstruction_jtextarea_instr1.setEditable(false);
        peekInstruction_jtextarea_instr1.setColumns(20);
        peekInstruction_jtextarea_instr1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        peekInstruction_jtextarea_instr1.setLineWrap(true);
        peekInstruction_jtextarea_instr1.setRows(5);
        peekInstruction_jtextarea_instr1.setText("Take a card from the draw pile, and either swap it with one of your cards or discard it and draw a second card to be swapped or thrown out.");
        peekInstruction_jtextarea_instr1.setWrapStyleWord(true);
        scrollPeek.setViewportView(peekInstruction_jtextarea_instr1);

        peekInstruction_jtextarea_instr2.setEditable(false);
        peekInstruction_jtextarea_instr2.setColumns(20);
        peekInstruction_jtextarea_instr2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        peekInstruction_jtextarea_instr2.setLineWrap(true);
        peekInstruction_jtextarea_instr2.setRows(5);
        peekInstruction_jtextarea_instr2.setText("Power cards have no value and if they are in a player's hand at the end of the round. They must be swapped for the top card of the deck.");
        peekInstruction_jtextarea_instr2.setWrapStyleWord(true);
        scrollPowerCards.setViewportView(peekInstruction_jtextarea_instr2);

        peekInstruction_jlabel_label1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        peekInstruction_jlabel_label1.setText("You've Drawn a Peek Card!");

        peekInstruction_jlabel_graphic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/11.png"))); // NOI18N

        peekInstruction_jlabel_graphic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/11.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(peekInstruction_jlabel_graphic1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(peekInstruction_jbutton_ok, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(scrollPeek, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addComponent(scrollPowerCards)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(peekInstruction_jlabel_graphic2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(peekInstruction_jlabel_label1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(peekInstruction_jlabel_label1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peekInstruction_jlabel_graphic1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPeek, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollPowerCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(peekInstruction_jlabel_graphic2))
                .addGap(18, 18, 18)
                .addComponent(peekInstruction_jbutton_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getRootPane().setDefaultButton(peekInstruction_jbutton_ok);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peekInstruction_jbutton_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peekInstruction_jbutton_okActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_peekInstruction_jbutton_okActionPerformed
    
    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeekInstructionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeekInstructionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeekInstructionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeekInstructionDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PeekInstructionDialog dialog = new PeekInstructionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton peekInstruction_jbutton_ok;
    private javax.swing.JLabel peekInstruction_jlabel_graphic1;
    private javax.swing.JLabel peekInstruction_jlabel_graphic2;
    private javax.swing.JLabel peekInstruction_jlabel_label1;
    private javax.swing.JTextArea peekInstruction_jtextarea_instr1;
    private javax.swing.JTextArea peekInstruction_jtextarea_instr2;
    private javax.swing.JScrollPane scrollPeek;
    private javax.swing.JScrollPane scrollPowerCards;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;
}
