/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.*;
import java.awt.*;


public class SwapDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form SwapDialog
     */
    public SwapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCard = new javax.swing.JLabel();
        Player2Card2 = new javax.swing.JLabel();
        Player2Card5 = new javax.swing.JLabel();
        Player2Card6 = new javax.swing.JLabel();
        Player2Card7 = new javax.swing.JLabel();
        Player2Card8 = new javax.swing.JLabel();
        Player2Card9 = new javax.swing.JLabel();
        Player2Card10 = new javax.swing.JLabel();
        comboPlayerCard = new javax.swing.JComboBox();
        comboOpponentCard = new javax.swing.JComboBox();
        buttonDiscard = new javax.swing.JButton();
        buttonSwap = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(labelCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 25, -1, -1));

        Player2Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(Player2Card2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 25, -1, -1));

        Player2Card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(Player2Card5, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 25, -1, -1));

        Player2Card6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(Player2Card6, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 25, -1, -1));

        Player2Card7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(Player2Card7, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 385, -1, -1));

        Player2Card8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(Player2Card8, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 385, -1, -1));

        Player2Card9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(Player2Card9, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 385, -1, -1));

        Player2Card10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N
        getContentPane().add(Player2Card10, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 385, -1, -1));

        comboPlayerCard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Card 1", "Card 2", "Card 3", "Card 4" }));
        getContentPane().add(comboPlayerCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 204, 83, -1));

        comboOpponentCard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Card 1", "Card 2", "Card 3", "Card 4" }));
        getContentPane().add(comboOpponentCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 237, 83, -1));

        buttonDiscard.setText("Discard");
        buttonDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiscardActionPerformed(evt);
            }
        });
        getContentPane().add(buttonDiscard, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 291, 83, 31));

        buttonSwap.setText("Swap");
        buttonSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSwap, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 291, 83, 31));

        jLabel7.setText("Card 1");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 128, -1, -1));

        jLabel8.setText("Card 2");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 128, -1, -1));

        jLabel9.setText("Card 3");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 128, -1, -1));

        jLabel10.setText("Card 4");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 128, -1, -1));

        jLabel11.setText("Card 1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 365, -1, -1));

        jLabel12.setText("Card 2");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 365, -1, -1));

        jLabel13.setText("Card 3");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 365, -1, -1));

        jLabel14.setText("Card 4");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 365, -1, -1));

        jLabel1.setText("Player 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 340, -1, -1));

        jLabel2.setText("Player 2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 153, -1, -1));

        jLabel3.setText("Choose Your Card:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 208, -1, -1));

        jLabel4.setText("Choose Opponent's Card:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 241, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void buttonDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiscardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDiscardActionPerformed

    private void buttonSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSwapActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SwapDialog dialog = new SwapDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Player2Card10;
    private javax.swing.JLabel Player2Card2;
    private javax.swing.JLabel Player2Card5;
    private javax.swing.JLabel Player2Card6;
    private javax.swing.JLabel Player2Card7;
    private javax.swing.JLabel Player2Card8;
    private javax.swing.JLabel Player2Card9;
    private javax.swing.JButton buttonDiscard;
    private javax.swing.JButton buttonSwap;
    private javax.swing.JComboBox comboOpponentCard;
    private javax.swing.JComboBox comboPlayerCard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelCard;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

}
