/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.*;
import java.awt.*;


public class SwapDialog extends javax.swing.JDialog {

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form SwapDialog
     */
    public SwapDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Player2Card1 = new javax.swing.JLabel();
        Player2Card2 = new javax.swing.JLabel();
        Player2Card4 = new javax.swing.JLabel();
        Player2Card3 = new javax.swing.JLabel();
        Player1Card2 = new javax.swing.JLabel();
        Player1Card1 = new javax.swing.JLabel();
        Player1Card4 = new javax.swing.JLabel();
        Player1Card3 = new javax.swing.JLabel();
        comboPlayerCard = new javax.swing.JComboBox();
        comboOpponentCard = new javax.swing.JComboBox();
        buttonSwapDiscard = new javax.swing.JButton();
        buttonSwap = new javax.swing.JButton();
        labelPlayer2Card1 = new javax.swing.JLabel();
        labelPlayer2Card2 = new javax.swing.JLabel();
        labelPlayer2Card3 = new javax.swing.JLabel();
        labelPlayer2Card4 = new javax.swing.JLabel();
        labelPlayer1Card1 = new javax.swing.JLabel();
        labelPlayer1Card2 = new javax.swing.JLabel();
        labelPlayer1Card3 = new javax.swing.JLabel();
        labelPlayer1Card4 = new javax.swing.JLabel();
        labelPlayer1 = new javax.swing.JLabel();
        labelPlayer2 = new javax.swing.JLabel();
        labelChooseCard = new javax.swing.JLabel();
        labelChooseOppCard = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        Player2Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        Player2Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        Player2Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        Player2Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        Player1Card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        Player1Card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        Player1Card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        Player1Card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/13tiny.png"))); // NOI18N

        comboPlayerCard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Card 1", "Card 2", "Card 3", "Card 4" }));

        comboOpponentCard.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Card 1", "Card 2", "Card 3", "Card 4" }));

        buttonSwapDiscard.setText("Discard");
        buttonSwapDiscard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapDiscardActionPerformed(evt);
            }
        });

        buttonSwap.setText("Swap");
        buttonSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSwapActionPerformed(evt);
            }
        });

        labelPlayer2Card1.setText("Card 1");

        labelPlayer2Card2.setText("Card 2");

        labelPlayer2Card3.setText("Card 3");

        labelPlayer2Card4.setText("Card 4");

        labelPlayer1Card1.setText("Card 1");

        labelPlayer1Card2.setText("Card 2");

        labelPlayer1Card3.setText("Card 3");

        labelPlayer1Card4.setText("Card 4");

        labelPlayer1.setText("Player 1");

        labelPlayer2.setText("Player 2");

        labelChooseCard.setText("Choose Your Card:");

        labelChooseOppCard.setText("Choose Opponent's Card:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Player2Card1)
                .addGap(18, 18, 18)
                .addComponent(Player2Card2)
                .addGap(18, 18, 18)
                .addComponent(Player2Card3)
                .addGap(18, 18, 18)
                .addComponent(Player2Card4))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(labelPlayer2Card1)
                .addGap(59, 59, 59)
                .addComponent(labelPlayer2Card2)
                .addGap(64, 64, 64)
                .addComponent(labelPlayer2Card3)
                .addGap(57, 57, 57)
                .addComponent(labelPlayer2Card4))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(labelPlayer2))
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(labelChooseCard)
                .addGap(18, 18, 18)
                .addComponent(comboPlayerCard, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(labelChooseOppCard)
                .addGap(18, 18, 18)
                .addComponent(comboOpponentCard, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(buttonSwap, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(buttonSwapDiscard, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(labelPlayer1))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(labelPlayer1Card1)
                .addGap(59, 59, 59)
                .addComponent(labelPlayer1Card2)
                .addGap(61, 61, 61)
                .addComponent(labelPlayer1Card3)
                .addGap(57, 57, 57)
                .addComponent(labelPlayer1Card4))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Player1Card1)
                .addGap(18, 18, 18)
                .addComponent(Player1Card2)
                .addGap(18, 18, 18)
                .addComponent(Player1Card3)
                .addGap(18, 18, 18)
                .addComponent(Player1Card4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Player2Card1)
                    .addComponent(Player2Card2)
                    .addComponent(Player2Card3)
                    .addComponent(Player2Card4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPlayer2Card1)
                    .addComponent(labelPlayer2Card2)
                    .addComponent(labelPlayer2Card3)
                    .addComponent(labelPlayer2Card4))
                .addGap(11, 11, 11)
                .addComponent(labelPlayer2)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelChooseCard))
                    .addComponent(comboPlayerCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(labelChooseOppCard))
                    .addComponent(comboOpponentCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSwap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSwapDiscard, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelPlayer1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPlayer1Card1)
                    .addComponent(labelPlayer1Card2)
                    .addComponent(labelPlayer1Card3)
                    .addComponent(labelPlayer1Card4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Player1Card1)
                    .addComponent(Player1Card2)
                    .addComponent(Player1Card3)
                    .addComponent(Player1Card4)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void buttonSwapDiscardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapDiscardActionPerformed
        // This would move the swap card to the discard pile
        /*
         * DiscardPileArray.add(card);
         * labelDiscard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/Cards/12.png")));
         */
    }//GEN-LAST:event_buttonSwapDiscardActionPerformed

    private void buttonSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSwapActionPerformed
        // This will actually do the swap between the cards
    }//GEN-LAST:event_buttonSwapActionPerformed
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwapDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SwapDialog dialog = new SwapDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Player1Card1;
    private javax.swing.JLabel Player1Card2;
    private javax.swing.JLabel Player1Card3;
    private javax.swing.JLabel Player1Card4;
    private javax.swing.JLabel Player2Card1;
    private javax.swing.JLabel Player2Card2;
    private javax.swing.JLabel Player2Card3;
    private javax.swing.JLabel Player2Card4;
    private javax.swing.JButton buttonSwap;
    private javax.swing.JButton buttonSwapDiscard;
    private javax.swing.JComboBox comboOpponentCard;
    private javax.swing.JComboBox comboPlayerCard;
    private javax.swing.JLabel labelChooseCard;
    private javax.swing.JLabel labelChooseOppCard;
    private javax.swing.JLabel labelPlayer1;
    private javax.swing.JLabel labelPlayer1Card1;
    private javax.swing.JLabel labelPlayer1Card2;
    private javax.swing.JLabel labelPlayer1Card3;
    private javax.swing.JLabel labelPlayer1Card4;
    private javax.swing.JLabel labelPlayer2;
    private javax.swing.JLabel labelPlayer2Card1;
    private javax.swing.JLabel labelPlayer2Card2;
    private javax.swing.JLabel labelPlayer2Card3;
    private javax.swing.JLabel labelPlayer2Card4;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = RET_CANCEL;

}
