/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author josh
 */
public class times_up extends javax.swing.JFrame {

    /**
     * Creates new form times_up
     */
    public times_up() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timesUp_label1 = new javax.swing.JLabel();
        timesUp_clockLabel2 = new javax.swing.JLabel();
        timesUp_clockLabel1 = new javax.swing.JLabel();
        timesUp_clockLabel3 = new javax.swing.JLabel();
        timesUp_clockLabel5 = new javax.swing.JLabel();
        timesUp_clockLabel4 = new javax.swing.JLabel();
        timesUp_jbutton_go = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        timesUp_label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        timesUp_label1.setText("Your Time is Up, this is your last turn. ");

        timesUp_clockLabel2.setBackground(new java.awt.Color(255, 255, 255));
        timesUp_clockLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        timesUp_clockLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timesUp_clockLabel2.setText("0");
        timesUp_clockLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        timesUp_clockLabel1.setBackground(new java.awt.Color(255, 255, 255));
        timesUp_clockLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        timesUp_clockLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timesUp_clockLabel1.setText("0");
        timesUp_clockLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        timesUp_clockLabel3.setBackground(new java.awt.Color(255, 255, 255));
        timesUp_clockLabel3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        timesUp_clockLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timesUp_clockLabel3.setText(":");

        timesUp_clockLabel5.setBackground(new java.awt.Color(255, 255, 255));
        timesUp_clockLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        timesUp_clockLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timesUp_clockLabel5.setText("0");
        timesUp_clockLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        timesUp_clockLabel4.setBackground(new java.awt.Color(255, 255, 255));
        timesUp_clockLabel4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        timesUp_clockLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timesUp_clockLabel4.setText("0");
        timesUp_clockLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        timesUp_jbutton_go.setText("Go");
        timesUp_jbutton_go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timesUp_jbutton_goActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(timesUp_label1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(timesUp_clockLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timesUp_clockLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timesUp_clockLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(timesUp_clockLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(timesUp_clockLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(timesUp_jbutton_go, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timesUp_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timesUp_clockLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesUp_clockLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesUp_clockLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesUp_clockLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesUp_clockLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(timesUp_jbutton_go, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void timesUp_jbutton_goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timesUp_jbutton_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timesUp_jbutton_goActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(times_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(times_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(times_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(times_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new times_up().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel timesUp_clockLabel1;
    private javax.swing.JLabel timesUp_clockLabel2;
    private javax.swing.JLabel timesUp_clockLabel3;
    private javax.swing.JLabel timesUp_clockLabel4;
    private javax.swing.JLabel timesUp_clockLabel5;
    private javax.swing.JButton timesUp_jbutton_go;
    private javax.swing.JLabel timesUp_label1;
    // End of variables declaration//GEN-END:variables
}
